Update setup task

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,36 +1,374 @@
-#!/bin/ruby
+#!/bin/sh
 
-def link(source, dest)
-  `ln -s $PWD/#{source} $HOME/.#{dest}`
-end
+linkup() {
+  if [ ! -h $2 ]; then
+    ln -sn $1 $2
+  fi
+  return
+}
 
-# Install zsh
-`mkdir -p ~/.oh-my-zsh/custom/plugins`
-link "zsh/koslow/", "oh-my-zsh/custom/plugins/koslow"
-link "zsh/code/", "oh-my-zsh/custom/plugins/code"
+# Here we go.. ask for the administrator password upfront and run a
+# keep-alive to update existing `sudo` time stamp until script has finished
+sudo -v
+while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
-# Link vimrc
-link "vim/vimrc", "vimrc"
-`mkdir ~/.vim`
-link "vim/autoload/", "vim/autoload"
-link "vim/colors/", "vim/colors"
-link "vim/doc/", "vim/doc"
-link "vim/ftdetect/", "vim/ftdetect"
-link "vim/ftplugin/", "vim/ftplugin"
-link "vim/plugin/", "vim/plugin"
-link "vim/spell/", "vim/spell"
-link "vim/surround/", "vim/surround"
-link "vim/syntax/", "vim/syntax"
-link "vim/syntax_checkers/", "vim/syntax_checkers"
-`git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle`
-`vim +BundleInstall +qall`
+# Install ZSH + Oh My ZSH
+if test ! $(which zsh); then
+  sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
+fi
+
+# Check for Homebrew,
+# Install if we don't have it
+if test ! $(which brew); then
+  echo "Installing homebrew..."
+  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
+fi
+
+# Update homebrew recipes
+echo "Updating homebrew..."
+brew update 2>/dev/null
+
+# Install GNU core utilities (those that come with OS X are outdated)
+brew install coreutils 2>/dev/null
+
+# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
+brew install findutils 2>/dev/null
+
+# Install Bash 4
+brew install bash 2>/dev/null
+
+# Install more recent versions of some OS X tools
+brew tap homebrew/dupes 2>/dev/null
+brew install homebrew/dupes/grep 2>/dev/null
+
+# Override defaut OSX bins
+if ! grep -q $(brew --prefix coreutils) "$HOME/.zshrc"; then
+  echo "\$PATH=$(brew --prefix coreutils)/libexec/gnubin:\$PATH" >> "$HOME/.zshrc"
+fi
+
+binaries=(
+  neovim
+  git
+  tmux
+  wget
+  the_silver_searcher
+  node
+  elixir
+  rbenv
+  ruby-build
+)
+
+echo "Installing brew binaries..."
+brew install ${binaries[@]} 2>/dev/null
+
+# Finish rbenv setup
+if ! grep -q "rbenv init" "$HOME/.zshrc"; then
+  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $HOME/.zshrc
+  echo 'eval "$(rbenv init -)"' >> $HOME/.zshrc
+fi
+
+brew install caskroom/cask/brew-cask 2>/dev/null
+
+# Apps
+apps=(
+  appcleaner
+  betterzipql
+  caffeine
+  dropbox
+  firefox
+  flux
+  google-chrome
+  qlcolorcode
+  qlimagesize
+  qlmarkdown
+  qlprettypatch
+  qlstephen
+  quicklook-csv
+  quicklook-json
+  skype
+  slack
+  spotify
+  webpquicklook
+)
+
+# Install apps to /Applications
+# Default is: /Users/$user/Applications
+echo "Installing apps via brew cask..."
+brew cask install --appdir="/Applications" ${apps[@]} 2>/dev/null
+
+# Link nvim
+linkup $PWD/nvim/ $HOME/.nvim
+linkup $PWD/nvim/nvimrc $HOME/.nvimrc
+
+# Install plug
+if [ ! -f $PWD/nvim/autoload/plug.vim ]; then
+  curl -fLo $PWD/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
+fi
+# Install nvim plugins
+nvim +PlugInstall +qall
 
 # Link tmux
-link "tmux/tmux.conf", "tmux.conf"
+linkup $PWD/tmux/tmux.conf $HOME/.tmux.conf
 
 # Link git
-link "git/gitconfig", "gitconfig"
-link "git/gitignore_global", "gitignore_global"
+linkup $PWD/git/gitconfig $HOME/.gitconfig
+linkup $PWD/git/gitignore_global $HOME/.gitignore_global
 
-# Link Ack
-link "ack/ackrc", "ackrc"
+# Cleanup brew
+echo "Cleaning up brew..."
+brew cleanup 2>/dev/null
+
+echo ""
+echo "Hiding the Time Machine, User, and Bluetooth icons"
+for domain in ~/Library/Preferences/ByHost/com.apple.systemuiserver.*; do
+  defaults write "${domain}" dontAutoLoad -array \
+    "/System/Library/CoreServices/Menu Extras/TimeMachine.menu" \
+    "/System/Library/CoreServices/Menu Extras/User.menu"
+done
+defaults write com.apple.systemuiserver menuExtras -array \
+  "/System/Library/CoreServices/Menu Extras/AirPort.menu" \
+  "/System/Library/CoreServices/Menu Extras/Battery.menu" \
+  "/System/Library/CoreServices/Menu Extras/Clock.menu"
+
+echo ""
+echo "Hiding the Spotlight icon"
+sudo chmod 600 /System/Library/CoreServices/Search.bundle/Contents/MacOS/Search
+
+echo ""
+echo "Disabling Spotlight indexing for any volume that gets mounted and has not yet been indexed before"
+sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"
+
+echo ""
+echo "Changing indexing order and disabling some search results in Spotlight"
+defaults write com.apple.spotlight orderedItems -array \
+    '{"enabled" = 1;"name" = "APPLICATIONS";}' \
+    '{"enabled" = 1;"name" = "SYSTEM_PREFS";}' \
+    '{"enabled" = 1;"name" = "DIRECTORIES";}' \
+    '{"enabled" = 1;"name" = "PDF";}' \
+    '{"enabled" = 1;"name" = "FONTS";}' \
+    '{"enabled" = 0;"name" = "DOCUMENTS";}' \
+    '{"enabled" = 0;"name" = "MESSAGES";}' \
+    '{"enabled" = 0;"name" = "CONTACT";}' \
+    '{"enabled" = 0;"name" = "EVENT_TODO";}' \
+    '{"enabled" = 0;"name" = "IMAGES";}' \
+    '{"enabled" = 0;"name" = "BOOKMARKS";}' \
+    '{"enabled" = 0;"name" = "MUSIC";}' \
+    '{"enabled" = 0;"name" = "MOVIES";}' \
+    '{"enabled" = 0;"name" = "PRESENTATIONS";}' \
+    '{"enabled" = 0;"name" = "SPREADSHEETS";}' \
+    '{"enabled" = 0;"name" = "SOURCE";}' \
+    '{"enabled" = 0;"name" = "MENU_DEFINITION";}' \
+    '{"enabled" = 0;"name" = "MENU_OTHER";}' \
+    '{"enabled" = 0;"name" = "MENU_CONVERSION";}' \
+    '{"enabled" = 0;"name" = "MENU_EXPRESSION";}' \
+    '{"enabled" = 0;"name" = "MENU_WEBSEARCH";}' \
+    '{"enabled" = 0;"name" = "MENU_SPOTLIGHT_SUGGESTIONS";}'
+# Load new settings before rebuilding the index
+killall mds > /dev/null 2>&1
+# Make sure indexing is enabled for the main volume
+sudo mdutil -i on / > /dev/null
+# Rebuild the index from scratch
+sudo mdutil -E / > /dev/null
+
+echo ""
+echo "Expanding the save panel by default"
+defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
+defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
+defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true
+
+echo ""
+echo "Automatically quit printer app once the print jobs complete"
+defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
+
+# Try e.g. `cd /tmp; unidecode "\x{0000}" > cc.txt; open -e cc.txt`
+echo ""
+echo "Displaying ASCII control characters using caret notation in standard text views"
+defaults write NSGlobalDomain NSTextShowsControlCharacters -bool true
+
+echo ""
+echo "Saving to disk, rather than iCloud, by default"
+defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
+
+echo ""
+echo "Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window"
+sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName
+
+echo ""
+echo "Check for software updates daily, not just once per week"
+defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
+
+echo ""
+echo "Removing duplicates in the 'Open With' menu"
+/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user
+
+echo ""
+echo "Disabling hibernation (speeds up entering sleep mode)"
+sudo pmset -a hibernatemode 0
+
+echo ""
+echo "Remove the sleep image file to save disk space"
+sudo rm /Private/var/vm/sleepimage
+echo "Creating a zero-byte file instead"
+sudo touch /Private/var/vm/sleepimage
+echo "and make sure it can't be rewritten"
+sudo chflags uchg /Private/var/vm/sleepimage
+
+echo ""
+echo "Disabling the sudden motion sensor (it's not useful for SSDs/current MacBooks)"
+sudo pmset -a sms 0
+
+echo ""
+echo "Disabling system-wide resume"
+defaults write com.apple.systempreferences NSQuitAlwaysKeepsWindows -bool false
+
+echo ""
+echo "Speeding up wake from sleep to 24 hours from an hour"
+# http://www.cultofmac.com/221392/quick-hack-speeds-up-retina-macbooks-wake-from-sleep-os-x-tips/
+sudo pmset -a standbydelay 86400
+
+echo ""
+echo "Increasing sound quality for Bluetooth headphones/headsets"
+defaults write com.apple.BluetoothAudioAgent "Apple Bitpool Min (editable)" -int 40
+
+echo ""
+echo "Enabling full keyboard access for all controls (enable Tab in modal dialogs, menu windows, etc.)"
+defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
+
+echo ""
+echo "Disabling press-and-hold for special keys in favor of key repeat"
+defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false
+
+echo ""
+echo "Setting a blazingly fast keyboard repeat rate"
+defaults write NSGlobalDomain KeyRepeat -int 0
+
+echo ""
+echo "Setting trackpad & mouse speed to a reasonable number"
+defaults write -g com.apple.trackpad.scaling 2
+defaults write -g com.apple.mouse.scaling 2.5
+
+echo ""
+echo "Turn off keyboard illumination when computer is not used for 5 minutes"
+defaults write com.apple.BezelServices kDimTime -int 300
+
+echo ""
+echo "Disabling display from automatically adjusting brightness"
+sudo defaults write /Library/Preferences/com.apple.iokit.AmbientLightSensor "Automatic Display Enabled" -bool false
+
+echo ""
+echo "Requiring password immediately after sleep or screen saver begins"
+defaults write com.apple.screensaver askForPassword -int 1
+defaults write com.apple.screensaver askForPasswordDelay -int 0
+
+echo ""
+echo "Enabling subpixel font rendering on non-Apple LCDs"
+defaults write NSGlobalDomain AppleFontSmoothing -int 2
+
+echo ""
+echo "Enabling HiDPI display modes (requires restart)"
+sudo defaults write /Library/Preferences/com.apple.windowserver DisplayResolutionEnabled -bool true
+
+echo ""
+echo "Showing icons for hard drives, servers, and removable media on the desktop"
+defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
+
+echo ""
+echo "Showing dotfiles in Finder by default"
+defaults write com.apple.finder AppleShowAllFiles TRUE
+
+echo ""
+echo "Using column view in all Finder windows by default"
+defaults write com.apple.finder FXPreferredViewStyle Clmv
+
+echo ""
+echo "Avoiding creation of .DS_Store files on network volumes"
+defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
+
+echo ""
+echo "Allowing text selection in Quick Look/Preview in Finder by default"
+defaults write com.apple.finder QLEnableTextSelection -bool true
+
+echo ""
+echo "Setting the icon size of Dock items to 36 pixels for optimal size/screen-realestate"
+defaults write com.apple.dock tilesize -int 36
+
+echo ""
+echo "Speeding up Mission Control animations and grouping windows by application"
+defaults write com.apple.dock expose-animation-duration -float 0.1
+defaults write com.apple.dock "expose-group-by-app" -bool true
+
+echo ""
+echo "Seting Dock to auto-hide and removing the auto-hiding delay"
+defaults write com.apple.dock autohide -bool true
+defaults write com.apple.dock autohide-delay -float 0
+defaults write com.apple.dock autohide-time-modifier -float 0
+
+echo ""
+echo "Privacy: Don't send search queries to Apple"
+defaults write com.apple.Safari UniversalSearchEnabled -bool false
+defaults write com.apple.Safari SuppressSearchSuggestions -bool true
+
+echo ""
+echo "Hiding Safari's bookmarks bar by default"
+defaults write com.apple.Safari ShowFavoritesBar -bool false
+
+echo ""
+echo "Hiding Safari's sidebar in Top Sites"
+defaults write com.apple.Safari ShowSidebarInTopSites -bool false
+
+echo ""
+echo "Disabling Safari's thumbnail cache for History and Top Sites"
+defaults write com.apple.Safari DebugSnapshotsUpdatePolicy -int 2
+
+echo ""
+echo "Enabling Safari's debug menu"
+defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
+
+echo ""
+echo "Making Safari's search banners default to Contains instead of Starts With"
+defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false
+
+echo ""
+echo "Removing useless icons from Safari's bookmarks bar"
+defaults write com.apple.Safari ProxiesInBookmarksBar "()"
+
+echo ""
+echo "Enabling the Develop menu and the Web Inspector in Safari"
+defaults write com.apple.Safari IncludeDevelopMenu -bool true
+defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
+defaults write com.apple.Safari "com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled" -bool true
+
+echo ""
+echo "Adding a context menu item for showing the Web Inspector in web views"
+defaults write NSGlobalDomain WebKitDeveloperExtras -bool true
+
+echo ""
+echo "Disabling the annoying backswipe in Chrome"
+defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool false
+defaults write com.google.Chrome.canary AppleEnableSwipeNavigateWithScrolls -bool false
+
+echo ""
+echo "Using the system-native print preview dialog in Chrome"
+defaults write com.google.Chrome DisablePrintPreview -bool true
+defaults write com.google.Chrome.canary DisablePrintPreview -bool true
+
+echo ""
+echo "Enabling UTF-8 ONLY in Terminal.app"
+defaults write com.apple.terminal StringEncodings -array 4
+
+echo ""
+echo "Preventing Time Machine from prompting to use new hard drives as backup volume"
+defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
+
+echo ""
+echo "Disabling local Time Machine backups"
+hash tmutil &> /dev/null && sudo tmutil disablelocal
+
+echo "Killing some open applications in order to take effect."
+
+find ~/Library/Application\ Support/Dock -name "*.db" -maxdepth 1 -delete
+for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
+  "Dock" "Finder" "Mail" "Messages" "Safari" "SystemUIServer" \
+  "Terminal" "Transmission"; do
+  killall "${app}" > /dev/null 2>&1
+done
